site_name: PG 680 Wiki
site_description: PG 680 Wiki
site_author: Constantin Chaumet
site_url: https://github.com/tudo-seal/pg-680-wiki
repo_name: tudo-seal/pg-680-wiki
repo_url: https://github.com/tudo-seal/pg-680-wiki
edit_uri: blob/main/docs
copyright: 'Copyright &copy; <a href="https://github.com/Jekannadar">Constantin Chaumet</a>: 2026-present'

docs_dir: wiki
site_dir: site
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: wiki/.overrides
  language: en
  favicon: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/seedling
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-off-outline
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Home:
    - About: index.md
  - Protokolle:
      - Template: protocols/template.md
      - protocols/*.md
  - FÃ¼r Betreuer: locked/
  - About:
    - Betreuer: about/authors.md

watch:
- wiki/

plugins:
  search: {}
  gen-files:
    scripts:
      - scripts/lock_folder.py
  literate-nav:
    nav_file: SUMMARY.md
  minify:
    minify_html: true
  git-revision-date-localized:
    type: date
    strict: false
  bibtex:
    bib_dir: "wiki/bibliographies"
    csl_file: "https://raw.githubusercontent.com/citation-style-language/styles/refs/heads/master/modern-language-association.csl"
  encryptcontent:
    title_prefix: ''
    summary: ''
    placeholder: 'Password'
    placeholder_user: User
    password_button_text: 'ENTER'
    decryption_failure_message: 'Wrong user name or password.'
    encryption_info_message: 'Legitimation required.'
    translations:
      de:
        title_prefix: ''
        summary: ''
        placeholder: 'Passwort'
        placeholder_user: Benutzer
        password_button_text: 'ENTER'
        decryption_failure_message: 'Falscher Benutzer oder Passwort.'
        encryption_info_message: 'Legitimation erforderlich.'
    password_button: True
    input_class: 'w3-input'
    button_class: 'w3-button w3-theme-l1 w3-hover-theme'
    hljs: False
    arithmatex: False
    mermaid2: False
    remember_keys: true
    remember_password: false
    remember_prefix: encryptcontent_plugin_
    encrypted_something:
      myToc: [ div, id ]
      myTocButton: [ div, id ]
    search_index: 'dynamically'
    webcrypto: true
    sign_files: 'encryptcontent-plugin.json'
    password_inventory:
      locked:
        supervisor: !ENV SUPERVISOR_PASSWORD

markdown_extensions:
  - attr_list:
  - admonition:
  - tables:
  - md_in_html:
  - toc:
        permalink: true
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      guess_lang: false
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:
  - pymdownx.blocks.tab:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tudo-seal/pg-680-wiki